services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: developerDB
      POSTGRES_PASSWORD: developerDB
      POSTGRES_DB: developerDB
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local