services:
  db:
    image: postgres:16.8
    container_name: postgres_db
    environment:
      POSTGRES_USER: developerDB
      POSTGRES_PASSWORD: developerDB
      POSTGRES_DB: developerDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis-trackmoney
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
