name: Java CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start PostgreSQL with Docker Compose
        run: docker compose -f ./docker-compose.yaml up -d

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run tests
        run: mvn test -Dspring.profiles.active=test

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Build JAR file
        run: mvn package
